# Generated by Django 5.1.4 on 2025-01-09 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "license_plate",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[("diesel", "Diesel"), ("gasolina", "Gasolina")],
                        default="Gasolina",
                        max_length=10,
                    ),
                ),
                ("tank_capacity", models.PositiveIntegerField()),
                ("horse_power", models.PositiveIntegerField()),
                ("year", models.PositiveIntegerField()),
                (
                    "brand",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand",
                        to="cars.brand",
                        verbose_name="Marca",
                    ),
                ),
            ],
        ),
    ]
