# Generated by Django 5.1.4 on 2025-01-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="brands/"),
        ),
        migrations.AddField(
            model_name="car",
            name="car_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
