# Generated by Django 5.1.4 on 2025-01-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_brand_logo_car_car_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="model",
        ),
        migrations.AddField(
            model_name="car",
            name="model",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
