# Generated by Django 5.1.4 on 2025-01-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0003_remove_brand_model_car_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="images/brands/"),
        ),
        migrations.AlterField(
            model_name="car",
            name="car_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/cars/"),
        ),
    ]
